import {imapSteps,recipeSource} from './recipes.js';
import {KEY,clone,initialData,localDate,emptyDaily,targets,routeBlock,hasSymptoms,evaluateProgress,parseBackup,validateRecordInput,validDate,pieceFractions} from './core.js';
import {load,save} from './storage.js';
const VERSION='1.0.2',BUILD='65348839015f';
const root=document.getElementById('em-demo'),el=id=>root.querySelector('#em-'+id),all=q=>[...root.querySelectorAll(q)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const unit=r=>({piece:'шт.',g:'г',ml:'мл'}[r.unit]);
const dateLabel=d=>validDate(d)?new Date(d+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'}):'не указан';
const names={pending:'Наблюдение продолжается',none:'Наблюдение завершено без симптомов',skin:'Сыпь / зуд / отёк',gut:'Желудочно-кишечные симптомы',other:'Другие симптомы',danger:'Опасные признаки'};
const diagnoses={nonige:'Лёгкая / среднетяжёлая не-IgE АБКМ',ige:'IgE-опосредованная АБКМ',fpies:'FPIES',severe:'Другая тяжёлая не-IgE форма',unknown:'Диагноз ещё не уточнён'};
const protocols={imap:'iMAP · 6 ступеней',individual:'Индивидуальное ведение в клинике'};
const assets={icon:'./assets/icon-192.png',photo:'./assets/author.jpg',qr:'./assets/taplink-qr.png'};
all('[data-em-author]').forEach(host=>host.append(el('author-template').content.cloneNode(true)));
all('[data-em-asset]').forEach(img=>img.src=assets[img.dataset.emAsset]);
let data,readOnly=false,dirty=false,view='today',editing=null,selectedStep=0,selectedDay=localDate(),recipeIndex=0,report=false,beforeAbout='today',pendingImport=null,deferredInstall=null,registration=null,updateRequested=false;
try{data=load(localStorage);}catch{data=initialData();readOnly=true;storageError('Не удалось прочитать сохранённый дневник. Данные не перезаписаны. Откройте «Данные и установка», сохраните исходную копию и восстановите исправную резервную копию.');}
selectedStep=data.plan.current;
function notice(text){el('status').textContent=text;el('status').hidden=!text;}
function storageError(text){el('storage-error').textContent=text;el('storage-error').hidden=!text;}
async function commit(change){
 if(readOnly){storageError('Сохранение отключено, чтобы не перезаписать непрочитанный дневник. Сначала сохраните исходную копию.');return false;}
 const run=()=>{const next=clone(data);change(next);data=save(localStorage,data,next);};
 try{if(navigator.locks)await navigator.locks.request(KEY,run);else run();storageError('');return true;}catch(e){storageError(e.message||'Не удалось сохранить данные.');return false;}
}
const block=()=>routeBlock(data.plan);
const hold=()=>block()||(data.paused?'Маршрут на паузе. Возобновление согласуйте с врачом.':'');
const progress=()=>evaluateProgress(data);
function todayDaily(){return data.daily.date===localDate()?data.daily:emptyDaily();}
function access(){all('[data-view="record"]').forEach(b=>b.disabled=Boolean(block())||readOnly);el('save-record').disabled=Boolean(block())||readOnly;}
function renderHeader(){el('profile-button').textContent=data.profile.name||'Профиль ребёнка';}
function renderDaily(){const d=todayDaily();const labels={well:'Ребёнок здоров; кожа, живот и стул без обострения',asthma:'Нет признаков обострения астмы / бронхообструкции',changes:'Нет новых изменений, требующих обсуждения с врачом',prepared:'Продукт, порция, время наблюдения и план помощи подготовлены'};el('daily-checks').innerHTML=Object.entries(labels).map(([k,v])=>`<label class="em-check"><input type="checkbox" data-daily="${k}" ${d[k]?'checked':''}><span>${v}</span></label>`).join('');el('daily-result').textContent=Object.keys(labels).every(k=>d[k])?'Чек-лист заполнен. Дальнейшие действия — по плану врача.':'Если пункт не выполнен или есть сомнение, отложите приём / повышение и уточните действия.';}
function renderHome(){
 el('today-label').textContent=new Date().toLocaleDateString('ru-RU',{day:'numeric',month:'long',weekday:'long'});
 const s=imapSteps[data.plan.current],h=hold();el('home-hold').textContent=h;el('home-hold').hidden=!h;el('current-step').textContent=h?'Домашний маршрут не активен':`Ступень ${data.plan.current+1} из 6`;el('current-name').textContent=h?'Нужна консультация аллерголога':s.name;el('current-protocol').textContent=protocols[data.plan.protocol];el('current-dose').hidden=Boolean(h);el('current-dose').textContent='Цель: '+s.portion;el('current-recipe').hidden=Boolean(block());renderDaily();
 const dates=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return localDate(d);});
 el('week').innerHTML=dates.map(d=>{const rr=data.records.filter(r=>!r.voided&&r.date===d),status=rr.some(hasSymptoms)?'symptom':rr.some(r=>r.kind==='intake'&&(r.symptom==='pending'||Date.parse(r.at)+r.observeHours*3600000>Date.now()))?'pending':rr.some(r=>r.kind==='intake')?'ok':rr.length?'skip':'empty';const label={symptom:'симптомы',pending:'наблюдение',ok:'завершено без симптомов',skip:'пропуск',empty:'нет записи'}[status];return `<button type="button" class="em-day" data-day="${d}" data-status="${status}" aria-pressed="${selectedDay===d}" aria-label="${dateLabel(d)}: ${label}"><span>${new Date(d+'T12:00:00').toLocaleDateString('ru-RU',{weekday:'short'})}</span>${Number(d.slice(-2))}<b>${{symptom:'!',pending:'◌',ok:'✓',skip:'—',empty:'·'}[status]}</b></button>`;}).join('');
 const rr=data.records.filter(r=>!r.voided&&r.date===selectedDay);el('day-detail').textContent=dateLabel(selectedDay)+': '+(rr.length?rr.map(r=>r.kind==='skip'?'пропуск':r.amount+' '+unit(r)+' · '+names[r.symptom]).join('; '):'нет записи');
}
function renderLadder(){el('ladder-caption').textContent='iMAP · шесть ступеней · только коровье молоко';el('ladder-hold').textContent=hold();el('ladder-hold').hidden=!hold();el('ladder-list').innerHTML=block()?'':imapSteps.map((s,i)=>`<button type="button" data-step="${i}" class="em-step" aria-pressed="${selectedStep===i}"><span class="em-step-num">${i+1}</span><span><strong>${s.name}</strong><small>${s.portion}${i===data.plan.current?' · текущая ступень':''}</small></span><span aria-hidden="true">›</span></button>`).join('');const s=imapSteps[selectedStep];el('step-detail').innerHTML=block()?'<h3>Домашняя лестница отключена</h3><p>Обсудите обследование и условия введения с аллергологом-иммунологом.</p>':`<p class="em-eyebrow">Ступень ${selectedStep+1}</p><h3>${s.name}</h3><p><strong>Целевая порция: ${s.portion}</strong></p><p class="em-note">${s.note}</p><button type="button" data-recipe="${selectedStep}" class="em-link">Продукт и приготовление</button><p class="em-small">Просмотр карточки не меняет текущую ступень.</p>`;}
function renderProgress(){const p=progress();el('progress-status').textContent=p.title;el('progress-status').className='em-notice '+(p.ready?'em-success':'');el('progress-count').hidden=Boolean(block());el('progress-count').innerHTML=`<h3>${p.count} из 3</h3><p class="em-note">Полная порция: ${imapSteps[data.plan.current].portion}. Завершённые наблюдения в текущем периоде.</p>`;el('progress-list').innerHTML=p.rows.map(r=>`<p class="em-note">${r.ok?'✓':'○'} ${esc(r.text)}</p>`).join('');el('review').textContent=data.question?'Вопрос добавлен в отчёт':'Добавить вопрос о переходе в отчёт';}
function renderRecipes(){el('recipe-list').innerHTML=imapSteps.map((s,i)=>`<button type="button" data-recipe="${i}" class="em-step"><span class="em-step-num">${i+1}</span><span><strong>${s.name}</strong><small>${s.portion}</small></span><span aria-hidden="true">›</span></button>`).join('');}
function renderRecipe(){const s=imapSteps[recipeIndex];el('recipe-content').innerHTML=`<p class="em-eyebrow">iMAP · ступень ${recipeIndex+1}</p><h2>${s.name}</h2><div class="em-notice">Целевая порция: ${s.portion}</div>${s.ingredients?`<div class="em-card"><h3>Состав</h3><p>${s.ingredients}</p><h3>Приготовление</h3><p>${s.method}</p></div><p class="em-note">Содержит коровье молоко и пшеницу. Проверьте переносимость остальных ингредиентов. Перед приготовлением сверьте полную карточку источника; варианты замен самостоятельно не выбирайте.</p><a href="${recipeSource}#page=${s.page}" target="_blank" rel="noopener noreferrer">Полная карточка Allergy UK · стр. ${s.page}</a>`:''}<p class="em-note">${s.note}</p><p class="em-small">Карточка носит справочный характер. Начало и увеличение порции согласуйте с врачом.</p>`;}
function entry(r,print=false){return `<article class="em-entry ${r.voided?'em-voided':''}"><div class="em-row"><strong>${dateLabel(r.date)} · ${esc(r.time)}</strong><span class="em-pill">${r.kind==='skip'?'Пропуск':r.amount+' '+unit(r)}</span></div><p>${imapSteps[r.step].name} · ступень ${r.step+1}</p><p class="em-small">Период ${r.revision}${r.revision!==data.plan.revision?' · прежние условия':''} · ${r.kind==='skip'?'Пропуск':r.phase==='buildup'?'Наращивание — не входит в счётчик':'Полная порция после наращивания'}</p><p>${r.voided?'Исключена из подсчёта · ':''}${r.kind==='skip'?esc(r.reason):names[r.symptom]}</p>${r.kind==='intake'?`<p class="em-small">Наблюдение: ${r.observeHours} ч. · цель ${r.target} ${unit(r)}${r.recipeMatch?'':' · рецепт / продукт отличался'}</p>`:''}${r.onset?'<p>Начало симптомов: '+esc(r.onset)+'</p>':''}${r.treatment?'<p>Помощь: '+esc(r.treatment)+'</p>':''}${r.note?'<p>'+esc(r.note)+'</p>':''}${!print?`<div class="em-actions"><button type="button" data-edit="${esc(r.id)}" class="em-link" ${block()||readOnly?'disabled':''}>Дополнить запись</button><button type="button" data-void="${esc(r.id)}" class="em-link">${r.voided?'Вернуть в подсчёт':'Исключить ошибочную запись'}</button></div>`:''}</article>`;}
function renderDiary(){const sorted=[...data.records].sort((a,b)=>b.at.localeCompare(a.at));el('entries').innerHTML=(block()?`<div class="em-notice em-alert">${esc(block())} История доступна для просмотра.</div>`:'')+(sorted.length?sorted.map(r=>entry(r)).join(''):'<p class="em-empty">Записей пока нет. После согласованного с врачом приёма добавьте продукт, порцию и наблюдение.</p>');el('report-log').innerHTML=sorted.map(r=>entry(r,true)).join('');el('counts').innerHTML=[['Приёмы',data.records.filter(r=>!r.voided&&r.kind==='intake').length],['С симптомами',data.records.filter(r=>!r.voided&&hasSymptoms(r)).length],['Пропуски',data.records.filter(r=>!r.voided&&r.kind==='skip').length]].map(([t,n])=>`<div><b>${n}</b><span>${t}</span></div>`).join('');const p=progress();el('report-body').innerHTML=`<h3>ЕмМолоко · отчёт для врача</h3><p>Ребёнок: ${esc(data.profile.name||'имя не указано')}${data.profile.dob?' · дата рождения '+dateLabel(data.profile.dob):''}</p><p class="em-small">Сформирован ${new Date().toLocaleString('ru-RU')}. Записи приведены по местному времени приёма.</p><p>${diagnoses[data.plan.phenotype]} · ${protocols[data.plan.protocol]}</p><p>${esc(hold()||'Пауза не отмечена')}</p><p>Связь: ${esc(data.plan.contact||'не указана')}</p><p>Контроль: ${dateLabel(data.plan.followup)}</p>${block()?'':`<p>Ступень ${data.plan.current+1}: ${imapSteps[data.plan.current].portion}. Засчитано ${p.count} из 3.</p><p>${esc(p.title)}</p>`}${data.question?'<div class="em-notice">Вопрос врачу: можно ли менять порцию или ступень?</div>':''}<p class="em-small">Самоотчёт родителей. Приложение не устанавливает причинную связь симптомов с продуктом и не подтверждает переносимость.</p>`;el('journal').hidden=report;el('report').hidden=!report;el('journal-toggle').setAttribute('aria-pressed',!report);el('report-toggle').setAttribute('aria-pressed',report);}
const fields={protocol:'protocol',phenotype:'phenotype','plan-step':'current','observe-hours':'observeHours',anaphylaxis:'anaphylaxis',traces:'traces','baked-reaction':'bakedReaction',asthma:'asthma',settled:'settled',contact:'contact',followup:'followup'};
function readPlan(){const p={...data.plan};for(const [id,key] of Object.entries(fields)){const n=el(id);p[key]=n.type==='checkbox'?n.checked:['current','observeHours'].includes(key)?Number(n.value):n.value.trim();}return p;}
function fillPlan(){el('plan-step').innerHTML=imapSteps.map((s,i)=>`<option value="${i}">${i+1}. ${s.name}</option>`).join('');for(const [id,key] of Object.entries(fields)){const n=el(id);if(n.type==='checkbox')n.checked=data.plan[key];else n.value=key==='observeHours'&&!data.plan[key]?'':data.plan[key];}el('plan-error').hidden=true;el('resume-area').hidden=!data.paused;el('resume-confirm').checked=false;planMessage();}
function planMessage(){const p=readPlan(),b=routeBlock(p),s=imapSteps[p.current];el('plan-message').textContent=b||'По выбранным условиям доступен маршрут iMAP. Начало и дальнейшие действия согласуются с аллергологом.';el('plan-message').className='em-notice '+(b?'em-alert':'');el('home-plan-fields').hidden=Boolean(routeBlock({...p,observeHours:p.observeHours||1}));el('plan-portion').textContent='Целевая порция: '+s.portion;el('plan-recipe-info').textContent=p.current<3?'Рецепт Allergy UK 2025 закреплён за ступенью.':'Продукт и порция iMAP. '+s.note;}
function recordContext(){return data.records.find(r=>r.id===editing)||{...targets(data.plan),step:data.plan.current};}
function openRecord(r){editing=r?.id||null;el('record-title').textContent=r?'Дополнить запись':'Записать приём';const c=r||{step:data.plan.current,...targets(data.plan)};el('record-context').textContent=`${imapSteps[c.step].name} · ступень ${c.step+1} · период ${c.revision}`;el('kind').value=r?.kind||'intake';el('date').value=r?.date||localDate();el('date').max=localDate();el('time').value=r?.time||new Date().toTimeString().slice(0,5);el('amount').value=r?.kind==='skip'?'':r?.amount??'';el('amount-label').textContent='Фактически съедено, '+unit(c);el('phase').value=r?.phase||'buildup';el('symptom').value=r?.symptom||'pending';el('recipe-match').checked=r?.recipeMatch??true;el('onset').value=r?.onset||'';el('treatment').value=r?.treatment||'';el('note').value=r?.note||'';el('skip-reason').value=r?.reason||'Согласованная пауза';el('record-error').hidden=true;el('record-target').textContent=`Цель этой записи: ${c.target} ${unit(c)}. Отмечайте фактически съеденное количество.`;updateRecord();}
function renderPortions(){const c=recordContext();el('portion-presets').hidden=c.unit!=='piece';if(c.unit!=='piece')return;el('portion-caption').textContent='Доля одного '+['печенья','маффина','блина'][c.step];el('portion-buttons').innerHTML=pieceFractions.map(f=>`<button type="button" data-portion="${f.label}" aria-pressed="${Number(el('amount').value)===f.amount}" aria-label="${f.label} изделия: ${f.approximate?'примерно ':''}${f.amount.toLocaleString('ru-RU',{maximumFractionDigits:6})} штуки">${f.label}<small>${f.approximate?'≈ ':''}${f.amount.toLocaleString('ru-RU',{maximumFractionDigits:6})} шт.</small></button>`).join('');}
function inputAt(){const old=data.records.find(r=>r.id===editing);if(old&&el('date').value===old.date&&el('time').value===old.time)return old.at;const d=new Date(el('date').value+'T'+el('time').value+':00');return Number.isFinite(+d)?d.toISOString():'';}
function updateRecord(){renderPortions();const skip=el('kind').value==='skip',s=el('symptom').value,c=recordContext();el('intake-fields').hidden=skip;el('skip-label').hidden=!skip;el('symptom-detail').hidden=skip||['pending','none'].includes(s);el('reaction-warning').hidden=skip||['pending','none'].includes(s);el('reaction-warning').innerHTML=s==='danger'?'<strong>Сначала помощь, потом запись.</strong> Вызывайте <a href="tel:112">112</a> / <a href="tel:103">103</a> и выполняйте план помощи. <button type="button" data-view="help" class="em-wide">Действия при реакции</button>':'Прекратите текущую пробу, выполните план помощи и свяжитесь с врачом. Повышение порции и переход откладываются.';const t=Date.parse(inputAt());el('observe-until').textContent=Number.isFinite(t)?`${c.observeHours} ч. наблюдения, до ${new Date(t+c.observeHours*3600000).toLocaleString('ru-RU')}. Окончание времени не заменяет отметку о симптомах.`:'';}
function renderSettings(){el('version').textContent=VERSION+' · '+BUILD;el('backup-status').textContent=`Записей: ${data.records.length}. Последнее сохранение: ${new Date(data.updatedAt).toLocaleString('ru-RU')}.`;}
function paint(){renderHeader();if(view==='today')renderHome();if(view==='ladder')renderLadder();if(view==='progress')renderProgress();if(view==='diary')renderDiary();if(view==='recipes')renderRecipes();if(view==='recipe')renderRecipe();if(view==='settings')renderSettings();access();}
function show(next,{force=false,retain=false}={}){if(dirty&&!force&&next!=='help'&&!confirm('Есть несохранённые изменения. Перейти без сохранения?'))return;if(!all('[data-panel]').some(p=>p.dataset.panel===next))next='today';if(next==='record'&&block())next='plan';if(next==='about'&&view!=='about')beforeAbout=view;view=next;dirty=false;all('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==view);all('.em-nav [data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===view));notice('');if(view==='plan'&&!retain)fillPlan();if(view==='record'&&!retain)openRecord();if(view==='profile'){el('child-name').value=data.profile.name;el('child-dob').value=data.profile.dob;el('child-dob').max=localDate();}if(view==='rules')el('rules-portions').innerHTML=imapSteps.map((s,i)=>`<p>${i+1}. ${s.portion}</p>`).join('');paint();window.scrollTo({top:0,behavior:'instant'});}
root.addEventListener('input',e=>{if(['plan','profile','record'].includes(view)&&e.target.id!=='em-resume-confirm'&&e.target.matches('input,select,textarea'))dirty=true;});
root.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.portion&&view==='record'&&recordContext().unit==='piece'){const f=pieceFractions.find(x=>x.label===b.dataset.portion);if(f){el('amount').value=f.amount;dirty=true;renderPortions();}return;}if(b.dataset.view)show(b.dataset.view);if(b.dataset.step!==undefined){selectedStep=Number(b.dataset.step);renderLadder();}if(b.dataset.recipe!==undefined){recipeIndex=Number(b.dataset.recipe);show('recipe');}if(b.dataset.day){selectedDay=b.dataset.day;renderHome();}if(b.dataset.edit&&!block()){show('record',{force:true,retain:true});openRecord(data.records.find(r=>r.id===b.dataset.edit));}if(b.dataset.void){const r=data.records.find(r=>r.id===b.dataset.void);if(!confirm(r.voided?'Вернуть запись в подсчёт?':'Исключить ошибочную запись из подсчёта? Она останется в истории.'))return;if(await commit(d=>{const x=d.records.find(x=>x.id===r.id);x.voided=!x.voided;x.updatedAt=new Date().toISOString();if(!x.voided&&hasSymptoms(x)){d.paused=true;d.pausedAt=x.updatedAt;}}))renderDiary();}});
root.addEventListener('change',async e=>{const k=e.target.dataset.daily;if(k){const checked=e.target.checked;if(await commit(d=>{if(d.daily.date!==localDate())d.daily=emptyDaily();d.daily[k]=checked;}))renderDaily();else e.target.checked=!checked;}});
const eligibility=new Set(['protocol','phenotype','anaphylaxis','traces','baked-reaction','asthma','settled']);
Object.keys(fields).forEach(id=>el(id).addEventListener('change',async()=>{if(eligibility.has(id)){const key=fields[id],p=readPlan();if(p[key]!==data.plan[key]){if(!await commit(d=>{d.plan[key]=p[key];d.plan.revision++;d.daily=emptyDaily();})){fillPlan();return;}}access();}planMessage();}));
el('save-plan').addEventListener('click',async()=>{const p=readPlan();if(!routeBlock({...p,observeHours:1})&&(!Number.isInteger(p.observeHours)||p.observeHours<1||p.observeHours>168)){el('plan-error').textContent='Укажите согласованную с врачом длительность наблюдения: 1–168 часов.';el('plan-error').hidden=false;return;}const changed=['current','observeHours'].some(k=>p[k]!==data.plan[k]);if(changed&&data.records.length&&!confirm('Изменение ступени или наблюдения начнёт новый подсчёт. Прежние записи сохранятся. Изменение согласовано с врачом?'))return;if(await commit(d=>{p.revision=d.plan.revision+(changed?1:0);d.plan=p;if(changed)d.daily=emptyDaily();})){selectedStep=p.current;show('today',{force:true});notice('План сохранён.');}});
el('save-profile').addEventListener('click',async()=>{const name=el('child-name').value.trim(),dob=el('child-dob').value;if(dob&&(!validDate(dob)||dob>localDate())){notice('Проверьте дату рождения.');return;}if(data.records.length&&(name!==data.profile.name||dob!==data.profile.dob)&&!confirm('Изменить профиль этого ребёнка? Записи останутся в его дневнике. Для другого ребёнка нужен отдельный дневник.'))return;if(await commit(d=>{d.profile={name,dob};})){show(data.guideRead?'today':'guide',{force:true});notice('Профиль сохранён.');}});
el('read-guide').addEventListener('change',()=>el('guide-done').disabled=!el('read-guide').checked);el('guide-done').addEventListener('click',async()=>{if(await commit(d=>d.guideRead=true))show('plan',{force:true});});
el('current-recipe').addEventListener('click',()=>{recipeIndex=data.plan.current;show('recipe');});el('about-back').addEventListener('click',()=>show(beforeAbout));
['kind','symptom','date','time'].forEach(id=>el(id).addEventListener('change',updateRecord));
el('amount').addEventListener('input',renderPortions);
el('save-record').addEventListener('click',async()=>{if(block()){show('plan',{force:true});return;}const old=data.records.find(r=>r.id===editing),p=targets(data.plan),kind=el('kind').value,now=new Date().toISOString();const context=old||{id:crypto.randomUUID(),revision:p.revision,step:p.current,recipe:p.recipeKey,unit:p.unit,target:p.target,observeHours:p.observeHours,voided:false,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'local'};const r={...context,date:el('date').value,time:el('time').value,at:inputAt(),kind,amount:kind==='skip'?0:Number(el('amount').value),phase:el('phase').value,symptom:kind==='skip'?null:el('symptom').value,recipeMatch:el('recipe-match').checked,onset:kind==='intake'&&!['none','pending'].includes(el('symptom').value)?el('onset').value:'',treatment:kind==='intake'?el('treatment').value.trim():'',note:el('note').value.trim(),reason:kind==='skip'?el('skip-reason').value:'',updatedAt:now};try{validateRecordInput(r);}catch(e){el('record-error').textContent=e.message;el('record-error').hidden=false;return;}if(await commit(d=>{const i=d.records.findIndex(x=>x.id===r.id);if(i<0)d.records.push(r);else d.records[i]=r;if(hasSymptoms(r)){d.paused=true;d.pausedAt=now;}})){editing=null;show('diary',{force:true});notice(hasSymptoms(r)?'Запись сохранена. Маршрут на паузе до решения врача.':'Запись сохранена на устройстве.');}});
el('pause').addEventListener('click',async()=>{if(await commit(d=>{d.paused=true;d.pausedAt=new Date().toISOString();})){show('today',{force:true});notice('Пауза сохранена. Возобновление — после согласования с врачом.');}});
el('resume').addEventListener('click',async()=>{if(!el('resume-confirm').checked){notice('Подтвердите, что возобновление согласовано с врачом.');return;}if(dirty){notice('Сначала сохраните изменённый план, затем подтвердите возобновление.');return;}if(block()){notice(block());return;}if(await commit(d=>{d.paused=false;d.pausedAt='';d.plan.revision++;d.daily=emptyDaily();})){show('today',{force:true});notice('Начат новый период наблюдения. Старые записи сохранены.');}});
el('review').addEventListener('click',async()=>{if(await commit(d=>d.question=true)){renderProgress();notice('Вопрос добавлен в отчёт. Врачу ничего не отправлено.');}});
el('journal-toggle').addEventListener('click',()=>{report=false;renderDiary();});el('report-toggle').addEventListener('click',()=>{report=true;renderDiary();});
function download(content,type,name){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
el('print-report').addEventListener('click',()=>{report=true;renderDiary();document.title='ЕмМолоко — отчёт для врача';window.print();document.title='ЕмМолоко — дневник молочной лестницы';});
el('export').addEventListener('click',()=>{let raw;try{raw=readOnly?localStorage.getItem(KEY):JSON.stringify(data,null,2);}catch{notice('Браузер не даёт прочитать сохранённые данные.');return;}if(!raw){notice('Сохранённых данных для копии нет.');return;}download(raw,'application/json',`em-moloko-backup-${localDate()}.json`);notice('Копия подготовлена. Убедитесь, что файл сохранился в загрузках.');});
el('import-file').addEventListener('change',async()=>{const file=el('import-file').files[0];if(!file)return;try{if(file.size>8_000_000)throw Error('Размер файла превышает 8 МБ.');pendingImport=parseBackup(await file.text());el('import-details').textContent=`Ребёнок: ${pendingImport.profile.name||'имя не указано'}. Записей: ${pendingImport.records.length}. Копия от ${new Date(pendingImport.updatedAt).toLocaleString('ru-RU')}. Текущий дневник будет заменён целиком; сначала сохраните его копию.`;el('import-preview').hidden=false;}catch(e){pendingImport=null;el('import-preview').hidden=true;notice(e.message);}el('import-file').value='';});
el('import-cancel').addEventListener('click',()=>{pendingImport=null;el('import-preview').hidden=true;});
el('import-apply').addEventListener('click',async()=>{if(!pendingImport||!confirm('Заменить текущий дневник выбранной резервной копией? Это не объединение записей.'))return;if(readOnly){notice('Исходные данные повреждены. Сохраните их копию, затем удалите данные через раздел ниже и повторите восстановление.');return;}const incoming=clone(pendingImport);if(await commit(d=>{Object.assign(d,incoming);if(d.records.some(r=>!r.voided&&r.revision===d.plan.revision&&hasSymptoms(r)))d.paused=true;})){pendingImport=null;el('import-preview').hidden=true;selectedStep=data.plan.current;show('today',{force:true});notice('Дневник восстановлен из копии.');}});
el('reset').addEventListener('click',()=>{if(!confirm('Удалить профиль, план и все записи с этого устройства? Продолжайте только после сохранения резервной копии.'))return;try{localStorage.removeItem(KEY);data=initialData();readOnly=false;dirty=false;pendingImport=null;el('import-preview').hidden=true;storageError('');show('profile',{force:true});notice('Создан пустой дневник.');}catch{storageError('Не удалось удалить данные.');}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
window.addEventListener('storage',e=>{if(e.key!==KEY)return;if(dirty){storageError('Данные изменились в другой вкладке. Обновите страницу перед сохранением.');return;}try{data=load(localStorage);selectedStep=data.plan.current;if(view==='plan')fillPlan();paint();notice('Дневник обновлён из другой вкладки.');}catch{readOnly=true;storageError('Не удалось прочитать обновление из другой вкладки.');}});
window.addEventListener('pageshow',()=>{if(!dirty)paint();});
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!dirty)paint();});
setInterval(()=>{if(!dirty&&['today','progress'].includes(view))paint();},60000);
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;el('install').hidden=false;});
el('install').addEventListener('click',async()=>{
 if(!deferredInstall)return;
 const prompt=deferredInstall;deferredInstall=null;el('install').hidden=true;
 try{await prompt.prompt();const choice=await prompt.userChoice;el('install-status').textContent=choice.outcome==='accepted'?'Запрос передан браузеру. Дождитесь завершения установки и проверьте иконку на главном экране.':'Установка отменена. Дневник можно продолжать вести в браузере.';}
 catch{el('install-status').textContent='Браузер не смог запустить установку. Откройте меню Chrome → «Добавить на главный экран». Если установка снова не проходит, пользуйтесь дневником по этой же ссылке.';}
});
window.addEventListener('appinstalled',()=>{deferredInstall=null;el('install').hidden=true;el('install-status').textContent='Браузер сообщил об установке. Откройте ЕмМолоко с главного экрана.';});
if(window.matchMedia('(display-mode: standalone)').matches||navigator.standalone===true)el('install-status').textContent='ЕмМолоко открыто как установленное приложение.';
el('update').addEventListener('click',()=>{if(dirty&&!confirm('Несохранённые изменения будут потеряны. Обновить приложение?'))return;dirty=false;updateRequested=true;registration?.waiting?.postMessage({type:'ACTIVATE'});});
if('serviceWorker' in navigator&&window.isSecureContext){navigator.serviceWorker.register('./sw.js').then(async reg=>{registration=reg;const ready=await navigator.serviceWorker.ready;el('offline-status').textContent=ready.active?'Приложение подготовлено для работы без интернета.':'Первое сохранение для работы без интернета…';const update=()=>{if(reg.waiting)el('update-bar').hidden=false;};update();reg.addEventListener('updatefound',()=>{reg.installing?.addEventListener('statechange',update);});}).catch(()=>{el('offline-status').textContent='Не удалось подготовить работу без интернета. Дневник сохраняется, но для открытия приложения пока нужна сеть.';});let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(updateRequested&&!reloading){reloading=true;location.reload();}});}else el('offline-status').textContent='Для установки и работы без интернета откройте приложение по защищённой ссылке HTTPS.';
show(data.guideRead?'today':'profile',{force:true});
